[package]
name = "solidity-decompiler"
version = "0.1.0"
edition = "2021"
authors = ["Pluto <https://twitter.com/homeslashpluto>"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"